/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dispatchdesktopapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class AddNewDispatch extends javax.swing.JFrame {

    /**
     * Creates new form AddNewDispatch
     */
    ArrayList<String> items;
    ArrayList<String> trucks;

    String oldData;
    public AddNewDispatch() {
        initComponents();
        items = new ArrayList<>();
        trucks = new ArrayList<>();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTruckId = new javax.swing.JTextField();
        tfItemId = new javax.swing.JTextField();
        tfSourceLoc = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDestinationLoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDispatchInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add New Dispatch");

        tfItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemIdActionPerformed(evt);
            }
        });

        tfSourceLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSourceLocActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Truck ID:");

        jLabel3.setText("Item ID:");

        jLabel4.setText("Dispatch Info:");

        jLabel5.setText("Source Loc:");

        jLabel6.setText("Destination Loc:");

        tfDestinationLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDestinationLocActionPerformed(evt);
            }
        });

        tfDispatchInfo.setColumns(20);
        tfDispatchInfo.setRows(5);
        jScrollPane1.setViewportView(tfDispatchInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(tfDestinationLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(tfSourceLoc)
                                .addComponent(tfItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(tfTruckId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSourceLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDestinationLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfTruckId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSourceLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSourceLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSourceLocActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String truckID = tfTruckId.getText().trim();
        String itemID = tfItemId.getText().trim();
        String info = tfDispatchInfo.getText().trim();
        String source = tfSourceLoc.getText().trim();
        String destination = tfDestinationLoc.getText().trim();

        if(truckID.isEmpty() || itemID.isEmpty()
            || info.isEmpty() || source.isEmpty() || destination.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Something is missing");
        }
        else
        {
             FileReader fr = null;
            BufferedReader br = null;
            
            try
            {
                boolean found = false;
                boolean found1 = false;
        
                fr = new FileReader(GlobalVariables.TRUCKFILE);
                br = new BufferedReader(fr);
                
                String line;
                while((line = br.readLine()) != null)
                {
                    String arr[] = line.split(",");
                    Object data[] = new Object[]{arr[0], arr[1], arr[2], arr[3]};
                    if(truckID.equals(arr[0]))
                    {
                        found = true;
                        break;
                    }
                }
                
                fr = new FileReader(GlobalVariables.ITEMFILE);
                br = new BufferedReader(fr);
                
                String line1;
                while((line1 = br.readLine()) != null)
                {
                    String arr1[] = line1.split(",");
                    Object data1[] = new Object[]{arr1[0], arr1[1], arr1[2], arr1[3]};
                    if(itemID.equals(arr1[0]))
                    {
                        found1 = true;
                        break;
                    }
                }
                if(found && found1)
                {
                    int confirm = JOptionPane.showConfirmDialog(rootPane, "Do you really want to save?");
                    if(confirm == 0)
                    {
                        FileWriter fw = null;
                        BufferedWriter bw = null;
                        try
                        {
                            fw = new FileWriter("dispatch.txt", true);
                            bw = new BufferedWriter(fw);
                            bw.write(truckID+","+itemID+","+source+","+destination+","+info);
                            bw.newLine();
                        }
                        catch(IOException ex)
                        {
                            System.out.println(ex.getMessage());
                        }
                        finally
                        {
                            if(bw != null)
                            {
                                try {
                                    bw.close();
                                } catch (IOException ex) {
                                    System.out.println(ex.getMessage());
                                }
                            }
                            if(fw != null){
                                try {
                                    fw.close();
                                } catch (IOException ex) {
                                    System.out.println(ex.getMessage());
                                }
                            }
                        }
                        java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                        new ViewDispatches().setVisible(true);
                            }
                        });
                        dispose(); 
                    }
                }
            }
            catch(IOException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DispatchMainMenu().setVisible(true);
            }
        });
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tfDestinationLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDestinationLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDestinationLocActionPerformed

    private void tfItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemIdActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfDestinationLoc;
    private javax.swing.JTextArea tfDispatchInfo;
    private javax.swing.JTextField tfItemId;
    private javax.swing.JTextField tfSourceLoc;
    private javax.swing.JTextField tfTruckId;
    // End of variables declaration//GEN-END:variables
}
